services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  users.webapp:
    image: userswebapp
    build:
      context: .
      dockerfile: Users.WebApp/Dockerfile
    depends_on:
      - mongo
