version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  users.webapp:
    image: userswebapp
    build:
      context: .
      dockerfile: Users.WebApp/Dockerfile
    depends_on:
      - mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      MONGO_CONNECTION_STRING: mongo
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    command: /bin/bash -c "
      dotnet dev-certs https &&
      dotnet dev-certs https --trust &&
      dotnet test"
